CREATE TABLE news (
	newsId INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(50) NOT NULL DEFAULT '',
	content MEDIUMTEXT NOT NULL,
	url TEXT,
	category VARCHAR(30),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (newsId)
);

CREATE TABLE interactions (
	interactionId INT NOT NULL AUTO_INCREMENT,
	type VARCHAR(50),
	newsId INT NOT NULL,
	studioId VARCHAR(250) NOT NULL,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (interactionId),
	FOREIGN KEY (newsId)
    REFERENCES news(newsId)
);