CREATE TABLE news (
	newsid INT NOT NULL,
	title VARCHAR(50) NOT NULL DEFAULT '',
	content MEDIUMTEXT NOT NULL,
	url VARCHAR(50),
	category VARCHAR(30),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (newsid)
);